function ael(q){return document.querySelector(q)}function products(){return RomTechData.loadProducts()}function setProducts(v){RomTechData.saveProducts(v);renderAdmin()}
function renderAdmin(){
 const root=ael("#adminRows"); if(!root)return; const rows=products();
 root.innerHTML=rows.map(p=>'<tr><td><input type="checkbox" class="pick" value="'+p.id+'"></td><td>'+esc(p.name)+'</td><td>'+esc(p.category)+'</td><td>'+money(p.salePrice||p.price)+'</td><td>'+p.stock+(p.stock<=Number(p.lowStock||3)?' <span class="tag">נמוך</span>':'')+'</td><td>'+esc(p.status)+'</td><td><button onclick="editProduct(\''+p.id+'\')">עריכה</button> <button onclick="duplicateProduct(\''+p.id+'\')">שכפול</button> <button onclick="deleteProduct(\''+p.id+'\')">מחיקה</button></td></tr>').join("");
 ael("#count").textContent=rows.length;ael("#low").textContent=rows.filter(p=>p.stock<=Number(p.lowStock||3)).length;
}
function openModal(){ael("#productModal").classList.add("open");ael("#productForm").reset();ael("#pid").value="";ael("#modalTitle").textContent="הוסף שטריימל חדש"}
function closeModal(){ael("#productModal").classList.remove("open")}
function editProduct(id){const p=products().find(x=>x.id===id);if(!p)return;openModal();ael("#modalTitle").textContent="עריכת מוצר";Object.entries(p).forEach(([k,v])=>{const f=ael('[name="'+k+'"]');if(!f)return;if(f.type==="checkbox")f.checked=!!v;else if(Array.isArray(v))f.value=v.join(", ");else f.value=v??""});ael("#pid").value=id}
function deleteProduct(id){if(!confirm("למחוק את המוצר?"))return;setProducts(products().filter(x=>x.id!==id))}
function duplicateProduct(id){const p=products().find(x=>x.id===id);if(!p)return;const c={...p,id:"rt-"+Date.now(),name:p.name+" — עותק",sku:"",slug:"",status:"draft"};setProducts([...products(),c])}
function selected(){return [...document.querySelectorAll(".pick:checked")].map(x=>x.value)}
function bulkApply(){const ids=selected();if(!ids.length)return alert("בחר מוצרים");const status=ael("#bulkStatus").value,category=ael("#bulkCategory").value,price=ael("#bulkPrice").value,stock=ael("#bulkStock").value;setProducts(products().map(p=>ids.includes(p.id)?{...p,...(status?{status}:{}),...(category?{category}:{}),...(price?{price:Number(price)}:{}),...(stock?{stock:Number(stock)}:{})}:p))}
function exportCsv(){const ps=products();const cols=["id","name","short","full","court","category","price","salePrice","cost","stock","lowStock","sku","barcode","height","teeth","fur","lining","box","embroidery","embroideryPrice","tags","status","seoTitle","seoDescription","slug"];const csv=[cols.join(","),...ps.map(p=>cols.map(k=>{let v=Array.isArray(p[k])?p[k].join("|"):p[k]??"";return '"'+String(v).replaceAll('"','""')+'"'}).join(","))].join("\n");const b=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"});const u=URL.createObjectURL(b);const a=document.createElement("a");a.href=u;a.download="romtech-products.csv";a.click();URL.revokeObjectURL(u)}
function parseCsv(text){const lines=text.split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];const parse=l=>{const out=[];let s="",q=false;for(let i=0;i<l.length;i++){const c=l[i];if(c==='"'&&l[i+1]==='"'){s+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===","&&!q){out.push(s);s="";continue}s+=c}out.push(s);return out};const headers=parse(lines[0]);return lines.slice(1).map(l=>{const vals=parse(l),o={};headers.forEach((h,i)=>o[h]=vals[i]??"");["price","salePrice","cost","stock","lowStock","height","teeth","embroideryPrice"].forEach(k=>{if(o[k]!=="")o[k]=Number(o[k])});o.embroidery=String(o.embroidery).toLowerCase()==="true";o.tags=o.tags?o.tags.split("|"):[];return o})}
document.addEventListener("DOMContentLoaded",()=>{renderAdmin();ael("#newBtn").onclick=openModal;ael("#closeModal").onclick=closeModal;ael("#productForm").addEventListener("submit",e=>{e.preventDefault();const fd=new FormData(e.target),o=Object.fromEntries(fd.entries());["price","salePrice","cost","stock","lowStock","height","teeth","embroideryPrice"].forEach(k=>o[k]=o[k]===""?null:Number(o[k]));o.embroidery=ael('[name="embroidery"]').checked;o.tags=(o.tags||"").split(",").map(x=>x.trim()).filter(Boolean);o.id=ael("#pid").value||"rt-"+Date.now();if(!o.slug)o.slug=o.name.toLowerCase().replace(/[^a-z0-9\u0590-\u05ff]+/g,"-").replace(/^-|-$/g,"");const ps=products(),i=ps.findIndex(x=>x.id===o.id);if(i>=0)ps[i]={...ps[i],...o};else ps.push(o);setProducts(ps);closeModal()});ael("#bulkApply").onclick=bulkApply;ael("#exportCsv").onclick=exportCsv;ael("#importCsv").addEventListener("change",async e=>{const f=e.target.files[0];if(!f)return;const rows=parseCsv(await f.text());if(rows.length&&confirm("לייבא "+rows.length+" מוצרים ולהחליף את הרשימה המקומית?"))setProducts(rows)})});