const DEFAULT_PRODUCTS=[
{id:"rt-001",name:"שטריימל סאטמר קלאסי",short:"מראה קלאסי, מאוזן ומהודר בעבודת יד.",full:"שטריימל קלאסי בעבודת יד עם התאמה מדויקת, גימור מוקפד ונוחות ללבישה ממושכת.",court:"סאטמר",category:"קלאסי",price:6900,salePrice:6490,cost:3900,stock:6,lowStock:3,sku:"RT-SAT-001",barcode:"729000000001",height:14,teeth:18,fur:"סאבל",lining:"שחור",box:"קופסת עץ",embroidery:true,embroideryPrice:150,tags:["רב-מכר"],status:"published",seoTitle:"שטריימל סאטמר קלאסי | רוםטק",seoDescription:"שטריימל סאטמר קלאסי בעבודת יד ובגימור מוקפד.",slug:"shtreimel-satmar-classic",images:[]},
{id:"rt-002",name:"שטריימל בעלז מהודר",short:"נפח עשיר ומראה חגיגי במיוחד.",full:"דגם מהודר בסגנון בעלז, עם בחירת פרווה איכותית ועבודת גימור ידנית.",court:"בעלז",category:"מהודר",price:8200,salePrice:null,cost:4700,stock:3,lowStock:3,sku:"RT-BEL-002",barcode:"729000000002",height:16,teeth:22,fur:"מינק",lining:"כחול",box:"קופסת עור",embroidery:true,embroideryPrice:150,tags:["חדש"],status:"published",seoTitle:"שטריימל בעלז מהודר | רוםטק",seoDescription:"דגם בעלז מהודר, עבודת יד ופרווה איכותית.",slug:"shtreimel-belz-premium",images:[]},
{id:"rt-003",name:"ספודיק גור",short:"קו גבוה, אלגנטי ומדויק למסורת גור.",full:"ספודיק במבנה גבוה ומאוזן, מיוצר בהתאמה אישית לפי מידות הלקוח.",court:"גור",category:"ספודיק",price:7600,salePrice:7190,cost:4300,stock:4,lowStock:2,sku:"RT-GER-003",barcode:"729000000003",height:16,teeth:26,fur:"שועל",lining:"אפור",box:"קופסת עץ",embroidery:false,embroideryPrice:150,tags:["מבצע"],status:"published",seoTitle:"ספודיק גור | רוםטק",seoDescription:"ספודיק גור אלגנטי בהתאמה אישית.",slug:"spodik-ger",images:[]}
];
function loadProducts(){try{return JSON.parse(localStorage.getItem("romtech_products"))||DEFAULT_PRODUCTS}catch{return DEFAULT_PRODUCTS}}
function saveProducts(items){localStorage.setItem("romtech_products",JSON.stringify(items))}
function loadOrders(){try{return JSON.parse(localStorage.getItem("romtech_orders"))||[]}catch{return []}}
function saveOrders(items){localStorage.setItem("romtech_orders",JSON.stringify(items))}
window.RomTechData={loadProducts,saveProducts,loadOrders,saveOrders,DEFAULT_PRODUCTS};